In [10]:
import numpy as np

In [11]:
from sklearn import linear_model

In [2]:
# valores_aleatorios = np.random.randint(50000, high=2000000, size=(10,))
# metragens_aleatorias = np.random.randint(10, high=200, size=(10,))

In [7]:
treinamento = np.vstack([valores_aleatorios, metragens_aleatorias]).T
treinamento

array([[ 770203,      49],
       [1285657,     166],
       [ 766172,      60],
       [ 414280,     162],
       [ 357982,     182],
       [ 575196,      77],
       [1932069,      35],
       [1119465,     168],
       [ 810716,      32],
       [ 961089,     130]])

In [8]:
resultados = np.array([0, 0, 1, 1, 1, 1, 0, 0, 0, 1])

In [15]:
dataset_treinamento = treinamento[0:8, :]
dataset_treinamento

array([[ 770203,      49],
       [1285657,     166],
       [ 766172,      60],
       [ 414280,     162],
       [ 357982,     182],
       [ 575196,      77],
       [1932069,      35],
       [1119465,     168]])

In [16]:
dataset_teste = treinamento[8:, :]
dataset_teste

array([[810716,     32],
       [961089,    130]])

In [17]:
resultados_treinamento = resultados[0:8]
resultados_treinamento

array([0, 0, 1, 1, 1, 1, 0, 0])

In [18]:
resultados_teste = resultados[8:]
resultados_teste

array([0, 1])

In [19]:
model = linear_model.LogisticRegression()

In [20]:
model.fit(dataset_treinamento, resultados_treinamento)

LogisticRegression()

In [21]:
model.score(dataset_teste, resultados_teste)

0.5

In [23]:
model.predict(dataset_teste)

array([0, 0])